### ISSUE TITLE
Handle PHP5.4 but no transliterator

### ISSUE THREAD

**Issue by Kroc** [Kroc/NoNonsenseForum#185]
There's a common situation where a user has PHP5.4, but the transliterator libs are not present and the title transliteration fails. We need to check for error and fall back to the <= PHP5.3 methods.

See: http://forum.camendesign.com/how-to-fix-parse-error-syntax-error-unexpected-t_object_operator-in-index-ph+1#6dbuokoy8g1e

**Comment by Zegnat** [comment]
Over at the forums, <b>Rogue</b> [writes in to say](http://forum.camendesign.com/posts-are-being-saved-as-_-rss-then-__1-rss+1#4426736l9ud) the `transliterator_list_ids` check seems to be working as expected: disabling `transliterator_transliterate` on his set-up where it wasn’t working.

**Comment by Zegnat** [comment]
Really happy to see this land, good work everyone who wrote in about this :+1:

**Comment by Kroc** [comment]
Thank you immensely for your work on this (and the UTF-8 handling), I haven't been able to work so diligently since my son has arrived so I grealty appreciate the motivation you bring to the project.
