### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by sbrl** [Kroc/NoNonsenseForum#237]
Do the NNF have a plugin system? I'm interested in perhaps writing a plugin or two if I were to set up an instance of the NNF on my server.

**Comment by Zegnat** [comment]
There is no system in place. Instead people are encouraged to [make themes](https://github.com/Kroc/NoNonsenseForum/wiki/How-to-Make-A-NoNonsense-Forum-Theme). Every theme has a <b>theme.php</b> file where arbitrary code (e.g. plugins) could be added.

An example is adding some code I wrote to the `theme_custom` function (of any theme) to enable inline images and video: http://forum.camendesign.com/embedd_youtube_videos_+1#24b46l14pukd

**Comment by sbrl** [comment]
@Zegnat Ah cool! I'll dig the through theme code then and do it that way.
